(* PerformanceBaseline.wl -- Stored timing baselines for Category E tests
   Generated by NKCalibrate[].  Re-run NKCalibrate[] after changing hardware. *)
<|
  "ODE_RK4_10000steps"       -> 0.8,
  "ODE_RK4_System_1000steps" -> 0.3,
  "Gauss_NodeCompute_n10"    -> 0.05,
  "Gauss_NodeMemoized_n10"   -> 0.001,
  "Gauss_Quad_1000calls"     -> 0.5,
  "LU_200x200"               -> 0.08,
  "CG_1000x1000"             -> 0.5,
  "Spline_1000pts"           -> 0.05,
  "BFGS_Rosenbrock50D"       -> 2.0
|>
